# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 265acb27b312fa974f2167b984842cb86c7c149ca4481848872aaa1a0b726d0dc9a11d9fc3c13a2b931a2a62b94964b7cb19a9bb4aafaae313b21ca7f76a2c62

test:
  secret_key_base: 8e002abeb591f0b1644ec9980877607881a802581216fdb21de3f081bba89099bf9089a762fa9980c359e23efbe7649de6242a67f10c978bc04be8502641f6fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
